295299
osisoft/PI-Adapter-BACnet-Docs pull request #87
Opened 2022-03-31 19:43 UTC by KNyce71

Minor edits in the BACnet Guide - part of the Adapter Doc Overhaul work. 

Thanks!

2022-03-31 20:10 UTC, osisoft-mbishop commented on content/configuration/configuration.md
>  This Quick Start guides you through setup of each configuration file available for PI Adapter for BACnet. As you complete each step, perform each required configuration to establish a data flow from
Just trying to avoid confusion based on the heading.

2022-03-31 20:21 UTC, osisoft-mbishop requested changes
Hey  @KNyce71 , I have a few nitpicks, but your changes look good for the most part.

2022-03-31 21:23 UTC, KNyce71 commented on content/health/adapter-health-for-bacnet.md
> -- [Next Health Message Expected](xref:NextHealthMessageExpectedForBACnet)
Great advice. Much appreciated.

2022-03-31 21:44 UTC, KNyce71 reviewed
Hi @osisoft-mbishop....thanks for the quick review! I changed the capital S in "Quick start" to lowercase. I think I've gotten all of your other comments as well. If you could finalize, I would appreciate it.

2022-04-01 01:26 UTC, osisoft-mbishop approved these changes

2022-04-01 01:27 UTC, merged